### ISSUE TITLE
Extract fuzzing test branches to separate, pre-assumed fuzzing test

### ISSUE THREAD

**Issue by Rubilmax** [morpho-labs/morpho-utils#27]
Basically extract every:

```solidity
function test(uint256 blabla) {
    if (condition) {
        expect(expectation1);
    } else {
        expect(expectation2);
    }
}
```

to:

```solidity
function testWhenCondition(uint256 blabla) {
    vm.assume(condition);
    expect(expectation1);
}

function testWhenNotCondition(uint256 blabla) {
    vm.assume(!condition);
    expect(expectation2);
}
```

**Comment by QGarchery** [comment]
Why ? Isn't it less efficient ?

**Comment by MathisGD** [comment]
It is, because we do more iteration in total. But as fuzzing inputs are a « black box », testing each branches with a if else does not ensure that those branches has been tested. With one fuzzing test with an assume per branch, we know that each of them has been fuzzed.
